server:
  port: 8090
  servlet:
    context-path: /client

  tomcat:
    threads:
      max: 5 # 생성할 수 있는 thread의 총 개수
      min-spare: 3 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 5 # 수립가능한 connection의 총 개수
    accept-count: 5 # 작업큐의 사이즈
    connection-timeout: 1000 # timeout 판단 기준 시간
